spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  profiles:
    default: default

jwt:
  header: Authorization
  # echo 'atto-research-assignment-by-jiyoung-lee-tulip-lee-is-good-very-good' | base64
  secret: YXR0by1yZXNlYXJjaC1hc3NpZ25tZW50LWJ5LWppeW91bmctbGVlLXR1bGlwLWxlZS1pcy1nb29kLXZlcnktZ29vZAo=
  token-validity-in-seconds: 86400
# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
components:
  securitySchemes:
    BearerAuth:
      type: http
      schema: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
